export const SHIFTS = {
    GENERATE_SHIFTS: 'GENERATE_SHIFTS',
    FETCH_SHIFTS_BY_DAY: 'FETCH_SHIFTS_BY_DAY',
    FETCH_SHIFTS_BY_WEEK: 'FETCH_SHIFTS_BY_WEEK',
    ADD_SHIFTS: 'ADD_SHIFTS',
    UPDATE_SHIFT: 'UPDATE_SHIFT'
}

export const TASKS = {
    GENERATE_TASKS: 'GENERATE_TASKS',
    FETCH_TASKS: 'FETCH_TASKS',
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK'
}

export const STAFF = {
    FETCH_STAFF: 'FETCH_STAFF',
    GET_STAFF_MEMBERS: 'GET_STAFF_MEMBERS',
    NEW_STAFF:'NEW_STAFF',
    DELETE_STAFF_MEMBER: 'DELETE_STAFF_MEMBER',
}
